# Generated by Django 5.2 on 2025-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_space', '0002_choix_pdf_question_choix_question_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
