# Generated by Django 5.2 on 2025-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_space', '0003_choix_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
